/** Central TanStack Query keys so invalidation stays consistent across screens. */
export const qk = {
  me: ["me"] as const,
  settings: ["settings"] as const,
  tables: (filters?: object) => ["tables", filters ?? {}] as const,
  tablesAll: ["tables"] as const,
  table: (id: number) => ["table", id] as const,
  categories: (filters?: object) => ["categories", filters ?? {}] as const,
  categoriesAll: ["categories"] as const,
  menu: (filters?: object) => ["menu", filters ?? {}] as const,
  menuAll: ["menu"] as const,
  menuItem: (id: number) => ["menu-item", id] as const,
  recipe: (id: number) => ["recipe", id] as const,
  recipes: ["recipes"] as const,
  orders: (filters?: object) => ["orders", filters ?? {}] as const,
  ordersAll: ["orders"] as const,
  order: (id: number) => ["order", id] as const,
  receipt: (id: number) => ["receipt", id] as const,
  inventory: (filters?: object) => ["inventory", filters ?? {}] as const,
  inventoryAll: ["inventory"] as const,
  inventoryOptions: ["inventory-options"] as const,
  inventoryItem: (id: number) => ["inventory-item", id] as const,
  movements: (filters?: object) => ["movements", filters ?? {}] as const,
  movementsAll: ["movements"] as const,
  dashboard: ["dashboard"] as const,
  salesReport: (filters: object) => ["sales-report", filters] as const,
  staff: (filters?: object) => ["staff", filters ?? {}] as const,
  staffAll: ["staff"] as const,
  auditLogs: (filters?: object) => ["audit-logs", filters ?? {}] as const,
};
